### ISSUE TITLE
Electron: RPC_COULD_NOT_CONNECT

### ISSUE THREAD

**Issue by F12-Syntex** [xhayper/discord-rpc#49] opened 2023-06-22 04:37 UTC
I've copy-pasted the example code provided onto my electron application.

```

import { Client } from "@xhayper/discord-rpc";

/* some code */

  const client = new Client({
    clientId: "" //MY CLIENT ID FROM THE DISCORD DEVELOPER PAGE
  });
  
  console.log("Discord RPC is starting...");

  client.login();

  client.on("ready", () => {
    console.log("Discord RPC is ready!");
      client.user?.setActivity({
          state: "Hello, world!"
      });
  });
```

However, I seem to get the following error.

UnhandledPromiseRejectionWarning: RPC_COULD_NOT_CONNECT: Could not connect
[error.txt](https://github.com/xhayper/discord-rpc/files/11828721/error.txt)

**Comment by xhayper** [comment] 2023-06-22 07:14
Are you using Discord PTB? or Discord Canary?

**Comment by xhayper** [comment] 2023-06-22 07:20
Actually, it might have to be something with Electron?

**Comment by F12-Syntex** [comment] 2023-06-22 20:10
> Actually, it might have to be something with Electron?

Possibly, any suggestions on how to tackle this error?

**Comment by xhayper** [comment] 2023-06-23 07:06
Maybe something to do with Electron sandboxing?

**Comment by F12-Syntex** [comment] 2023-06-23 07:33
> Maybe something to do with Electron sandboxing?

I made a fresh Nodejs project and tried running it there, but I'm getting the same issue, 🤔 

I've made sure discord is open during testing, confirmed that other presence ( such as vsc ) work, and lastly I've copy-pasted the Discord developer portal > My app > OAuth2 > CLIENT ID into the clientId property of Client 

`
const client = new Client({
  clientId: client_id,
});
`

**Comment by xhayper** [comment] 2023-06-23 08:31
Can you make a git repo so i can see?

**Comment by xhayper** [comment] 2023-06-25 02:36
Hey, i gonna go ahead and close this issue, because i think it is caused by Electron itself and not the library, if you would like me to check if it was caused by my library itself, you can reply to this issue with the github repository so i can re-produce the issue.

**Comment by mateie** [comment] 2023-07-15 07:09
I made a github repo, since I have the same issue here.

https://github.com/mateie/discord-rpc-project

**Comment by xhayper** [comment] 2023-07-15 07:30
thank you!

**Comment by xhayper** [comment] 2023-07-15 07:32
If possible, please specify below

OS:
Discord Version:
if using Linux, are you using flatpak or snap or?:

**Comment by mateie** [comment] 2023-07-15 07:33
Stable 213510 (8831bfd) 
Host 1.0.9015 (34898) 
Windows 10 64-Bit (10.0.19045)

**Comment by xhayper** [comment] 2023-07-15 07:34
Also, if possible, please create a new issue instead of necro this one!

**Comment by xhayper** [comment] 2023-07-15 07:47
also i am not available but i will check it out when i am back home

**Closed** 2023-07-15 12:56 UTC
Labels: bug

**Comment by xhayper** [comment] 2023-07-15 13:00
@mateie @F12-Syntex sorry for the very VERY late fix but it should be fixed now

**Comment by F12-Syntex** [comment] 2023-07-15 13:02
> @mateie @F12-Syntex sorry for the very VERY late fix but it should be fixed now

Much appreciated, I'll have to check it out when I get back home.

**Comment by xhayper** [comment] 2023-07-15 13:07
yeah, it turn out that my old code will only check dirname of the ipc path, which, in windows, will return false, and make it so the lib can't find the path, there's also optimization update coming soon too

**Comment by mateie** [comment] 2023-07-16 00:42
Nothing to apologize for, thank you for fixing it for us <3
